#!/usr/bin/env ruby
require 'fileutils'

path = "#{ENV['HOME']}/current/public/uploads"

if File.directory?(path)
  FileUtils.mv(path, "#{path}.old")
elsif File.symlink?(path)
  FileUtils.rm(path)
end

FileUtils.symlink("#{ENV['HOME']}/public/uploads", path)
