default:
  youtube:
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC8dwPSQ5DOJGtwhmcNhNjSw # ヤンマガch 講談社
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCrJ0g7xuENFH5h4XyuDGltw # 18man
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCyh0e1_dwRavk1NTLaAPklA # SUKIYA TV
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC0wPMrt3i6yGYafBsZGt9Dg # ビンビン美女ちゃんねる
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCheS6QSlUT1vTmLTeWk9pZA # アサ芸チャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCoAUHXbimNOE9dG9I1uiVlQ # かわいい芸能人まとめチャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCnsAlmY7PFYmjO2VW3qqlEQ # Idol Fans
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCS4HQy_5YTYuuq3CCb56N2A # グラビア tv
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCF8WygxYEa85kL3GH-YP65A # アイドルグラビア動画まとめ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCJ7ADpy43cJfFVwKSZTfSbQ # AKBお宝まとめ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UChsWqaK0dkFnH9X6dtaJKzg # 巨乳系☆グラビアアイドル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCKeuFLxVs38-oOeJqxI0GoA # max10 fm
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC8yN3HAs3BjA0LS6-roQO1Q # 可愛い・癒し系☆グラビアアイドル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCIen5wjL7sBAckv_06rqWGA # Japan Sexy Idol
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCsh1AaSrqyx0DKxmGsh04jA # Japanese Idols Collection
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCNzpj-FNysXoC6QB8N1x6AQ # Hot Girl Japan!
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCsdYYMrEaU8dwiEyhs_kccA # JPN20130116
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC28n9xdO0CbVZ5qedXoauSQ # HAYABUSA
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCpcLX1X6hf0zS2sj1EqNl6g # エロゲ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCscCzWI0gLfABt1vrikaLxA # グラッチェ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCgk-wn4Wtxfj6q5ZnQkaYeA # mania minami
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCwOvNwaIRSso0USo3eCQyqQ # 三愛水着楽園
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCS_OaxaDePrzgEUkIno2V9Q # Sweety Ellie
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC3LOtSJioG-cb9aZKsNhdEg # I'm Tim
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCYiPH3U4oSUkCyg6MDXkg_A # グラビアアイドル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCeyu92mBL_7Ef3qA5I3txVg # グラビア学園 YouTubeチャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCjLT4Rn1L8JVJ1gu53hgppQ # horizonjapan1
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC9wJf-yLQ3vwNhkea3OFABg # Simson Black Aturan
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCmGwDrMZk8g5z1Whn21YZYw # Swimsuit Channel
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCbg51tNi2bVnu9yvL-kGHIQ # おっチャンネル（１回の裏）
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCG9QGvMg993m9lCd-ZjtGPw # 週プレYOUTUBEチャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCw855t6RuS_tc2m2qitfbwQ # IIIIIXCLIPS
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCQE4xNVlAI2FSnnqvNOuV1g # Miracle24
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCsY1SO7rS175xnZjQMcOZeA # gravure02
  niconico:
    - http://www.nicovideo.jp/tag/磯山さやか?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/尾崎ナナ?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/杉原杏璃?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/橋本マナミ?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/大島優子?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/今野杏南?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/久松郁実?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/倉科カナ?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/山本彩?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/渡辺美優紀?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/大川藍?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/丸高愛実?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/柳ゆり菜?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/丸高愛実?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/護あさな?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/星名美津紀?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/久松郁実?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/葉月あや?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/武田玲奈?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/鷹羽澪?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/篠崎愛?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/佐山彩香?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/佐野ひなこ?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/白石麻衣?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/山本彩?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/星名美津紀?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/渡辺美優紀?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/小池里奈?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/倉持由香?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/岸明日香?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/おのののか?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/石川恋?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/筧美和子?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/足立梨花?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/吉木りさ?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/兎月りお?sort=f&rss=2.0
    - http://www.nicovideo.jp/tag/片岡沙耶?sort=f&rss=2.0
