default:
  youtube:
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCG5C6ymGnKWJXuiVc6mthBw # 動画ちゃんねるオススメ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCjKIgYRHudpMiFxwHPfrMcw # gilgamesh
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC8dwPSQ5DOJGtwhmcNhNjSw # ヤンマガch 講談社
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCrJ0g7xuENFH5h4XyuDGltw # 18man
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCyh0e1_dwRavk1NTLaAPklA # SUKIYA TV
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCheS6QSlUT1vTmLTeWk9pZA # アサ芸チャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCoAUHXbimNOE9dG9I1uiVlQ # かわいい芸能人まとめチャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCF8WygxYEa85kL3GH-YP65A # アイドルグラビア動画まとめ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCJ7ADpy43cJfFVwKSZTfSbQ # AKBお宝まとめ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCNzpj-FNysXoC6QB8N1x6AQ # Hot Girl Japan!
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCsdYYMrEaU8dwiEyhs_kccA # JPN20130116
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCpcLX1X6hf0zS2sj1EqNl6g # エロゲ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCwOvNwaIRSso0USo3eCQyqQ # 三愛水着楽園
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCeyu92mBL_7Ef3qA5I3txVg # グラビア学園 YouTubeチャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCjLT4Rn1L8JVJ1gu53hgppQ # horizonjapan1
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCmGwDrMZk8g5z1Whn21YZYw # Swimsuit Channel
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCbg51tNi2bVnu9yvL-kGHIQ # おっチャンネル（１回の裏）
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCG9QGvMg993m9lCd-ZjtGPw # 週プレYOUTUBEチャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCw855t6RuS_tc2m2qitfbwQ # IIIIIXCLIPS
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCsY1SO7rS175xnZjQMcOZeA # gravure02
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCNn6HrjlTCvQuJCxIMCz54g # tetsuro24
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCmp9xyIDtNJOdkbaxquGGtA # Girls.com
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCQgy68aUf3M5cuOubWMqUbw # エンタメセレクション
    - https://www.youtube.com/feeds/videos.xml?user=desktopgalcollection # DGC YouTube チャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCv9nvfVm-1OLQp0eO2DoQXg # AKI TSUCHI
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCXkNWLBZcFdS8iYVhved-PQ # Kimberly Macon
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC35dgDbbl91CFgYrPS9v8sA # LOVEPOP ４K動画ちゃんねる
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC-RMfD2nq5cfkcdkwqiVh_g # NEWS IDOL
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCLeCJphWd7hSD0AR0sdibfw # とある芸能人のワキ動画
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCQTjcfJnYO725KVVO42oRhA # GirlsTube
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCvz44P_Jly_WV-2L5OdGI1Q # しんのすけVENUS
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCfyawFau0aAFOO8TJFzFiJw # さや姉
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCPiL4QJdqqiyOKDXReKNeTA # 白泉社 ヤングアニマル
  niconico:
    - http://www.nicovideo.jp/tag/#{tag名}?sort=f&rss=2.0
  fc2:
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=92175954 # アイドルワン
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=11692696 # エスデジタル
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=12648105 # japan
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=90574862 # イーネットフロンティア
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=45142242 # U18.tv
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=52350916 # 株式会社アイロゴス
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=62749320 # アイマックスch
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=34602261 # きゅうすた／FP姫
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=57806661 # ムービープラネット
    - http://video.fc2.com/rss/member/mb_feed.php?mbid=71352278 # SpiceVisual
