default:
  youtube:
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC8dwPSQ5DOJGtwhmcNhNjSw # ヤンマガch 講談社
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCrJ0g7xuENFH5h4XyuDGltw # 18man
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCyh0e1_dwRavk1NTLaAPklA # SUKIYA TV
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC0wPMrt3i6yGYafBsZGt9Dg # ビンビン美女ちゃんねる
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCheS6QSlUT1vTmLTeWk9pZA # アサ芸チャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCoAUHXbimNOE9dG9I1uiVlQ # かわいい芸能人まとめチャンネル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCnsAlmY7PFYmjO2VW3qqlEQ # Idol Fans
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCS4HQy_5YTYuuq3CCb56N2A # グラビア tv
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCF8WygxYEa85kL3GH-YP65A # アイドルグラビア動画まとめ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCJ7ADpy43cJfFVwKSZTfSbQ # AKBお宝まとめ
    - https://www.youtube.com/feeds/videos.xml?channel_id=UChsWqaK0dkFnH9X6dtaJKzg # 巨乳系☆グラビアアイドル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCKeuFLxVs38-oOeJqxI0GoA # max10 fm
    - https://www.youtube.com/feeds/videos.xml?channel_id=UC8yN3HAs3BjA0LS6-roQO1Q # 可愛い・癒し系☆グラビアアイドル
    - https://www.youtube.com/feeds/videos.xml?channel_id=UCIen5wjL7sBAckv_06rqWGA # Japan Sexy Idol
