default:
  title: グラビア動画BOX　〜セクシーグラビア動画見放題〜
  description: 人気グラビアアイドルのおすすめ動画をまとめているグラビア動画BOX。かわいい、エロい、美人なアイドルや巨乳・美乳アイドルなど幅広く掲載しています。
  words:
    - おすすめ
    - オススメ
    - 注目
    - 人気
    - 新着
    - 美女
    - 美少女
    - 美人
    - ロリ
    - 可愛い
    - かわいい
    - カワイイ
    - セクシー
    - お色気
    - 巨乳
    - 美乳
    - 爆乳
    - ビキニ
    - 水着
    - 下着
    - 微乳
    - 谷間
    - ペチャパイ
    - 神乳
    - お尻
    - 美尻
    - 巨尻
    - 四つん這い
    - 着衣

