development:
  database: gravure-tube_development
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['MYSQL_ROOT_PW'] %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  username: sqale_3109f2709b
  password: 422927da41273c09731900ef4f0ee92a41d283551db3705e
  database: sqale_3109f2709b
  host: mysql001.sqale.jp
