development:
  database: gravure-tube_development
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['MYSQL_ROOT_PW'] %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  username: root
  password: idoldaisuki
  database: gravure_tube_production
  host: localhost
